version: 2
jobs:
  targetplatform:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1000m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-targetplatform-{{ .Branch }}-{{ checksum "maven-cache-version" }}
      - run: |
          ant targetplatform -Dupload=true -Dversion="${MINORTAG}.${CIRCLE_BUILD_NUM}"
          ssh -o StrictHostKeyChecking=no navajo@repo.dexels.com "mkdir -p /var/www/html/repo/eclipse/3rdparty_${MINORTAG}.${CIRCLE_BUILD_NUM}/"
          scp -r targetplatform/target/repository/* navajo@repo.dexels.com:/var/www/html/repo/eclipse/3rdparty_${MINORTAG}.${CIRCLE_BUILD_NUM} 
      - save_cache:
            paths:
              - ~/.m2
            key: maven-repo-targetplatform-{{ .Branch }}-{{ checksum "maven-cache-version" }}
  build:
    branch:
      only:
        newbuild
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1000m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "maven-cache-version" }}
      - run: |
          ant alldistros -Ddocker=false -Dupload=false -Dbundles=core.cfg,dependency.cfg -Dversion=${MINORTAG}.${CIRCLE_BUILD_NUM} -debug
          ls -l target
      - store_artifacts:
          path: ~/repo/target/dexels-base.tar.gz
          destination: dexels-base.tgz
      - save_cache:
            paths:
              - ~/.m2
            key: maven-repo-v1-{{ .Branch }}-{{ checksum "maven-cache-version" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - temp
            - targetplatform
  package:
    machine:
      image: circleci/classic:edge
    steps:
      - attach_workspace:
          at: ~/repo
      - run: |
          docker --version
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          TAG=${MINORTAG}.$CIRCLE_BUILD_NUM
          echo "Building tag: $TAG"
          cd ~/repo
          ls -l
          docker build -t dexels/dexels-base:$TAG -t dexels/dexels-base:latest temp
          docker push dexels/dexels-base:$TAG
          docker push dexels/dexels-base:latest
          curl -X POST --header "Content-Type: application/json" -d '{"branch":"master"}' "https://circleci.com/api/v1.1/project/github/dexels/navajo-container/build?circle-token=${CIRCLE_TOKEN}"
          curl -X POST --header "Content-Type: application/json" -d '{"branch":"master"}' "https://circleci.com/api/v1.1/project/github/dexels/navajo-streams/build?circle-token=${CIRCLE_TOKEN}"
          curl -X POST --header "Content-Type: application/json" -d '{"branch":"master"}' "https://circleci.com/api/v1.1/project/github/dexels/navajo-vaadin/build?circle-token=${CIRCLE_TOKEN}"
workflows:
  version: 2
  workflow:
    jobs:
      - targetplatform
      - build
      - package:
          requires:
            - build
