version: 2.1
jobs:
  targetplatform:
    docker:
      - image: circleci/openjdk:11-jdk
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1000m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-targetplatform-{{ .Branch }}-{{ checksum "maven-cache-version" }}
      - run:
          name: Run Ant createtargetplatform
          command: |
            ant targetplatform -Dversion="${MINORTAG}.${CIRCLE_BUILD_NUM}"
            cd targetplatform
            mvn -s "../.circleci/conf/settings.xml" install -B -U -ff
            cd ..
      - run:
          name: Upload(scp) thirdparty P2 Environment to repo.dexels.com
          command: |
            SUFFIX=`[[ $CIRCLE_BRANCH = "master" ]] && echo "" || echo "-$CIRCLE_BRANCH"`
            echo "Using Suffix $SUFFIX"
            ssh -o StrictHostKeyChecking=no navajo@repo.dexels.com "mkdir -p /var/www/html/repo/eclipse/3rdparty_${MINORTAG}.${CIRCLE_BUILD_NUM}${SUFFIX}/"
            scp -r targetplatform/target/repository/* navajo@repo.dexels.com:/var/www/html/repo/eclipse/3rdparty_${MINORTAG}.${CIRCLE_BUILD_NUM}${SUFFIX}
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-targetplatform-{{ .Branch }}-{{ checksum "maven-cache-version" }}

      - run:
          name: Update navajo dependency on dexels-base to latest dexels-base build version (Triggers CI build on navajo)
          command: |
            mkdir ~/navajocheckout
            cd  ~/navajocheckout
            git clone https://${GITHUB_PERSONAL_TOKEN}@github.com/Dexels/navajo.git -b ${CIRCLE_BRANCH} --depth 1
            ls -l
            cd navajo/setup/com.dexels.navajo.target
            BRANCH="${CIRCLE_BRANCH}"  DEXELS_BASE_BUILD="${CIRCLE_BUILD_NUM}"  ./updateversion.sh
            # Push changes
            git config credential.helper 'cache --timeout=120'
            git config user.email "Dexels Butler"
            git config user.name "butler@dexels.com"
            git add .
            echo "commiting changes"
            git commit --allow-empty -m "Update via CircleCI"
            git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/Dexels/navajo.git ${CIRCLE_BRANCH}
            echo "push complete"

  package:
    docker:
      - image: circleci/openjdk:11-jdk
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1000m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "maven-cache-version" }}
      - run:
          # TODO cleanup antfiles remove all unneeded targets
          name: Runt Ant alldistros (dockersetup)
          command: |
            ant alldistros -Ddocker=false -Dupload=false -Dbundles=core.cfg -Dversion=${MINORTAG}.${CIRCLE_BUILD_NUM} -debug
            ls -l target
      - store_artifacts:
          path: ~/repo/target/dexels-base.tar.gz
          destination: dexels-base.tgz
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "maven-cache-version" }}

      # See https://circleci.com/docs/2.0/building-docker-images/
      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Log in with docker registries
          command: |
            docker --version
            echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin

      - run:
          name: Docker build and push dexels-base image
          command: |
            TAGSUFFIX=`[[ $CIRCLE_BRANCH = "master" ]] && echo "" || echo "-${CIRCLE_BRANCH}"`
            TAG=${MINORTAG}.${CIRCLE_BUILD_NUM}${TAGSUFFIX}
            echo "Building tag: $TAG"
            cd ~/repo
            ls -l
            export GIT_REMOTE=$(git config --get remote.origin.url)
            export GIT_COMMIT=$(git rev-parse HEAD)
            echo "Adding remote: ${GIT_REMOTE} and commit: ${GIT_COMMIT}"
            IMAGE=dexels/dexels-base
            docker build --build-arg DEXELS_BASE_COMMIT=${GIT_COMMIT} --build-arg DEXELS_BASE_REMOTE=${GIT_REMOTE} -t ${IMAGE}:$TAG temp
            docker push ${IMAGE}:$TAG
            if [ $CIRCLE_BRANCH = "master" ]; then
              docker tag ${IMAGE}:$TAG ${IMAGE}:latest
              docker push ${IMAGE}:latest
            fi

      # - run:
      #     name: Trigger navajo CircleCI build
      #     command: |
            # if [ $CIRCLE_BRANCH = "master" ]; then
            #   curl -X POST \
            #     --header "Content-Type: application/json" \
            #     --header "Circle-Token: ${CIRCLE_TOKEN}" \
            #     -d "{\"branch\":\"${CIRCLE_BRANCH}\"}" \
            #     "https://circleci.com/api/v1.1/project/github/dexels/navajo/build"
            # fi
            # curl -X POST \
            #   --header "Content-Type: application/json" \
            #   --header "Circle-Token: ${CIRCLE_TOKEN}" \
            #   -d "{\"branch\":\"${CIRCLE_BRANCH}\"}" \
            #   "https://circleci.com/api/v1.1/project/github/dexels/navajo-streams/build"

workflows:
  version: 2
  workflow:
    jobs:
    - targetplatform:
        context:
        - dexels_docker_hub
        filters:
          branches:
            only:
            - master
            - test
            - sendratosports

    - package:
        context:
        - dexels_docker_hub
        filters:
          branches:
            only:
            - master
            - test
            - sendratosports
