version: 2.1
jobs:
  db_targetplatform:
    docker:
      - image: cimg/openjdk:17.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1000m
      TERM: dumb
      ANT_VERSION: apache-ant-1.10.15
      ANT_HOME: /opt/apache-ant-1.10.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-targetplatform-{{ .Branch }}-{{ checksum "maven-cache-version" }}

      # Install Ant manually from Apache
      - run:
          name: Install Ant manually
          command: |
            sudo apt-get update
            sudo apt-get install -y wget
            wget https://downloads.apache.org/ant/binaries/$ANT_VERSION-bin.tar.gz
            sudo tar -xzf $ANT_VERSION-bin.tar.gz -C /opt/
            sudo ln -s $ANT_HOME /opt/ant

      - run:
          name: Run Ant createtargetplatform
          command: |
            export PATH=/opt/ant/bin:$PATH
            ant targetplatform -Dversion="${MINORTAG}.${CIRCLE_BUILD_NUM}"
            cd targetplatform
            mvn -s "../.circleci/conf/settings.xml" install -B -U -ff
            cd ..

      - run:
          name: Upload(scp) thirdparty P2 Environment to repo.dexels.com
          command: |
            SUFFIX=`[[ $CIRCLE_BRANCH = "main" ]] && echo "" || echo "-$CIRCLE_BRANCH"`
            echo "Using Suffix $SUFFIX"
            ssh -o StrictHostKeyChecking=no dexelsbutler@repo.dexels.com "mkdir -p /var/www/html/repo/eclipse/3rdparty_${MINORTAG}.${CIRCLE_BUILD_NUM}${SUFFIX}/"
            scp -r targetplatform/target/repository/* dexelsbutler@repo.dexels.com:/var/www/html/repo/eclipse/3rdparty_${MINORTAG}.${CIRCLE_BUILD_NUM}${SUFFIX}

      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-targetplatform-{{ .Branch }}-{{ checksum "maven-cache-version" }}

      - run:
          name: Update navajo dependency on dexels-base to latest dexels-base build version (Triggers CI build on navajo)
          command: |
            mkdir ~/navajocheckout
            cd  ~/navajocheckout
            git clone https://${GITHUB_PERSONAL_TOKEN}@github.com/Sendrato/navajo.git -b "$CIRCLE_BRANCH" --depth 1
            ls -l
            cd navajo/setup/com.dexels.navajo.target
            DEXELS_BASE_BRANCH="${CIRCLE_BRANCH}"  DEXELS_BASE_BUILD="${CIRCLE_BUILD_NUM}"  ./updateversion.sh
            # Push changes
            git config credential.helper 'cache --timeout=120'
            git config user.email "Dexels Butler"
            git config user.name "butler@dexels.com"
            git add .
            echo "committing changes"
            git commit --allow-empty -m "Update via CircleCI"
            git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/Sendrato/navajo.git main
            echo "push complete"

  db_docker:
    docker:
      - image: circleci/openjdk:17-jdk
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1000m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "maven-cache-version" }}
      - run:
          # TODO cleanup antfiles remove all unneeded targets
          name: Runt Ant alldistros (dockersetup)
          command: |
            ant alldistros -Ddocker=false -Dupload=false -Dbundles=core.cfg -Dversion=${MINORTAG}.${CIRCLE_BUILD_NUM} -debug
            ls -l target
      - store_artifacts:
          path: ~/repo/target/dexels-base.tar.gz
          destination: dexels-base.tgz
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "maven-cache-version" }}

      # See https://circleci.com/docs/2.0/building-docker-images/
      - setup_remote_docker
      - run:
          name: Log in with docker registries
          command: |
            docker --version
            echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin

      - run:
          name: Docker build and push dexels-base image
          command: |
            TAGSUFFIX=`[[ $CIRCLE_BRANCH = "main" ]] && echo "" || echo "-${CIRCLE_BRANCH}"`
            TAG=${MINORTAG}.${CIRCLE_BUILD_NUM}${TAGSUFFIX}
            echo "Building tag: $TAG"
            cd ~/repo
            ls -l
            export GIT_REMOTE=$(git config --get remote.origin.url)
            export GIT_COMMIT=$(git rev-parse HEAD)
            echo "Adding remote: ${GIT_REMOTE} and commit: ${GIT_COMMIT}"
            IMAGE=dexels/dexels-base
            docker build --build-arg DEXELS_BASE_COMMIT=${GIT_COMMIT} --build-arg DEXELS_BASE_REMOTE=${GIT_REMOTE} -t ${IMAGE}:$TAG temp
            docker push ${IMAGE}:$TAG
            if [ $CIRCLE_BRANCH = "main" ]; then
              docker tag ${IMAGE}:$TAG ${IMAGE}:latest
              docker push ${IMAGE}:latest
            fi

workflows:
  version: 2
  main:
    jobs:
    - db_targetplatform:
        context:
        - dexels_docker_hub
        filters:
          branches:
            only:
            - main
            - test

    # - db_docker:
    #     context:
    #     - dexels_docker_hub
    #     filters:
    #       branches:
    #         only:
    #         - main
    #         - test
