version: 2
jobs:
  targetplatform:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1000m
      TERM: dumb
    steps:
      - checkout
      - run: |
          ant -lib ant/lib/jsch-0.1.55.jar targetplatform -Dupload=true -Dversion="3.1.${CIRCLE_BUILD_NUM}"
          ssh -o StrictHostKeyChecking=no navajo@repo.dexels.com "mkdir -p /var/www/html/repo/eclipse/3rdparty_3.1.${CIRCLE_BUILD_NUM}/"
          scp -r targetplatform/target/repository/* navajo@repo.dexels.com:/var/www/html/repo/eclipse/3rdparty_3.1.${CIRCLE_BUILD_NUM} 
  build:
    branch:
      only:
        newbuild
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1000m
      TERM: dumb
    steps:
      - checkout
      - run: |
          ant -Ddocker=false -Dupload=false -debug
          rm -rf temp/target temp/container temp/pom.xml
          ls -l
          pwd
      - persist_to_workspace:
          root: ~/repo
          paths:
            - temp
            - targetplatform
  package:
    machine:
      image: circleci/classic:edge
    steps:
      - attach_workspace:
          at: ~/repo
      - run: |
          docker --version
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          TAG=${MINORTAG}.$CIRCLE_BUILD_NUM
          echo "Building tag: $TAG"
          cd ~/repo
          ls -l
          docker build -t dexels/dexels-base:$TAG -t dexels/dexels-base:latest temp
          docker push dexels/dexels-base:$TAG
          docker push dexels/dexels-base:latest
workflows:
  version: 2
  workflow:
    jobs:
      - targetplatform
      - build
      - package:
          requires:
            - build
